prodcursos:
  host: "s-cursosdb-api-4nw6zl.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  basPath: "/api"
  protocol: "HTTPS"
  
usuarios:
  host: "s-usuariossalesforce-api-4nw6zl.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  basPath: "/api"
  protocol: "HTTPS"
  
pago:
  host: "s-ecommerce-api-4nw6zl.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  basPath: "/api"
  protocol: "HTTPS"  
  