sfdc:
  username: "pablo.cerda2002@gmail.com"
  password: "elcrack009"
  securityToken: "q5KyOVZkIJudWym1EWfrh3gQE"

SNS:
  AccesKey: "ASIA3IULDR6YURCNA27Y"
  SecretKey: "d6FE32X2FwgvGnvaiS6Fnj+OPUz/CRgwc17yKtxj"
  token: "FwoGZXIvYXdzEGsaDEJ/IQSUk80M5pjefiLEATvmd4nK3XOqW324m+mV/fmD2Ktyr9rR2GZN/7Z/sLFfHSzxv6Dj2JMKGijMw3dx5tHrBFWaHkkB0x56gI6gzTqHNEH5hwnMkCRJ2+e3m33LRVIuEYFBaTSYg+P1tM/SecOslEZuGVv/w5JQ7hpgURBrE+0yFQDfT6qtAZblLOFq8dSx3SH3bhPbgTjCRLdv9AhCV2CGyit+cIyiEVm2kr+ModR82QnjKNX12vzE/TqlkzfLexl3hj7/CN1mZSTKWCSbWMYo/rTNqwYyLSJ3N/ojOBeaPaFQ61x+oG2wFjap7Uq/zswQht9s6rKeW4XLHx/nHgj+yYSNPA=="
