usuarios:
  host: "s-usuariossalesforce-api-4nw6zl.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  basePath: "/api"
  protocol: "HTTPS"
  
lambda:
  host: "s-recomendacion-api.us-e2.cloudhub.io"
  port: "8081" 